# fly.toml app configuration file generated for aqualobby on 2024-01-15T17:23:48+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aqualobby"
primary_region = "ams"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "7.4"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"
  DB_CONNECTION = "mysql"
  DB_HOST = "sql11.freesqldatabase.com"
  DB_DATABASE = "dbaqua"
  DB_USERNAME = "adminaqua"
  # ZyenaBVBUy

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
